name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/setup-clojure@8.0
      with:
        cli: 'latest'
    - name: Compile
      run: |
        npm install
        clojure -M:prod
        cp target/public/js/main.js resources/public/js/main.js
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./resources/public
